sudo: false

language: go

go: 1.4

git:
  submodules: false

before_install:
  - git submodule update --init --recursive --remote

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz
  - tar xzvf hugo_0.31.1_Linux-64bit.tar.gz
  - chmod +x hugo

script:
  - chmod +x deploy_ghpages.sh
  - if [[ $TRAVIS_BRANCH = master ]]; then ./hugo && echo seedstack.org >| public/CNAME; fi
  - if [[ $TRAVIS_BRANCH = beta ]]; then ./hugo -d beta -b http://beta.seedstack.org/ && echo beta.seedstack.org >| beta/CNAME; fi
  - if [[ $TRAVIS_BRANCH = dev ]]; then ./hugo -d dev -b http://dev.seedstack.org/ && echo dev.seedstack.org >| dev/CNAME; fi

after_success:
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]]; then ./deploy_ghpages.sh && (curl http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2Fseedstack.org%2Fsitemap.xml > /dev/null || :); fi
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = beta ]]; then ./deploy_ghpages.sh beta beta; fi
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = dev ]]; then ./deploy_ghpages.sh dev dev; fi
