sudo: false

language: go

go: 1.4

addons:
  apt:
    packages:
      - oracle-java8-installer
      - graphviz

git:
  submodules: false

cache:
  directories:
    - node_modules
  
before_install:
  - git submodule update --init --recursive --remote
  - IFS='-' read -r -a ARCHIVE <<< "$TRAVIS_BRANCH"

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
  - tar xzvf hugo_0.18.1_Linux-64bit.tar.gz
  - chmod +x hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64
  - npm install

script:
  - chmod +x deploy_ghpages.sh
  - grunt lunr-index
  - if [[ $TRAVIS_BRANCH = master ]]; then ./hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 && echo seedstack.org >| public/CNAME; fi
  - if [[ $TRAVIS_BRANCH = beta ]]; then ./hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 -d beta -b http://beta.seedstack.org/ && echo beta.seedstack.org >| beta/CNAME; fi
  - if [[ $TRAVIS_BRANCH = dev ]]; then ./hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 -d dev -b http://dev.seedstack.org/ && echo dev.seedstack.org >| dev/CNAME; fi
  - if [[ $TRAVIS_BRANCH = archive-* ]]; then ./hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 -d archives/${ARCHIVE[1]} -b http://seedstack.org/archives/${ARCHIVE[1]}/; fi

after_success:
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]]; then ./deploy_ghpages.sh && (curl http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2Fseedstack.org%2Fsitemap.xml > /dev/null || :); fi
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = beta ]]; then ./deploy_ghpages.sh beta beta; fi
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = dev ]]; then ./deploy_ghpages.sh dev dev; fi
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = archive-* ]]; then ./deploy_ghpages.sh archives archives; fi
