baseurl = "http://seedstack.org/"
MetaDataFormat = "yaml"

[params]
  description = "SeedStack, Clean Java Development"
  author = "The SeedStack authors"

  "javax.mail.version" = "1.4.8"
  "ch.qos.logback.version" = "1.2.3"
  "org.apache.kafka.version" = "2.2.0"

  "org.seedstack.version" = "19.11"
  "org.seedstack.version-notes" = "19.11"

  "org.seedstack.maven.version" = "2.7.5"

  "org.seedstack.poms.version" = "3.4.8"

  "org.seedstack.shed.version" = "1.1.6"
  "org.seedstack.coffig.version" = "3.1.4"
  "org.seedstack.seed.version" = "3.9.1"
  "org.seedstack.business.version" = "4.3.0"

  "org.seedstack.addons.audit.version" = "3.0.0"
  "org.seedstack.addons.aws.version" = "1.0.0"
  "org.seedstack.addons.cci.version" = "1.1.0"
  "org.seedstack.addons.consul.version" = "1.0.0"
  "org.seedstack.addons.crud.version" = "1.0.0"
  "org.seedstack.addons.datasecurity.version" = "1.0.0"
  "org.seedstack.addons.elasticsearch.version" = "3.0.0"
  "org.seedstack.addons.feign.version" = "1.3.1"
  "org.seedstack.addons.flyway.version" = "1.0.0"
  "org.seedstack.addons.i18n.version" = "4.1.0"
  "org.seedstack.addons.io.version" = "3.0.0"
  "org.seedstack.addons.javamail.version" = "3.0.0"
  "org.seedstack.addons.jcache.version" = "3.0.0"
  "org.seedstack.addons.jdbc.version" = "3.0.2"
  "org.seedstack.addons.jmh.version" = "1.0.2"
  "org.seedstack.addons.jms.version" = "3.1.0"
  "org.seedstack.addons.jpa.version" = "4.1.0"
  "org.seedstack.addons.kafka.version" = "2.0.0"
  "org.seedstack.addons.ldap.version" = "3.0.0"
  "org.seedstack.addons.metrics.version" = "1.0.0"
  "org.seedstack.addons.modelmapper.version" = "1.0.0"
  "org.seedstack.addons.mongodb.version" = "3.0.1"
  "org.seedstack.addons.monitoring.version" = "3.1.0"
  "org.seedstack.addons.mqtt.version" = "2.1.0"
  "org.seedstack.addons.neo4j.version" = "2.0.0"
  "org.seedstack.addons.netflix.version" = "1.2.1"
  "org.seedstack.addons.oauth.version" = "1.1.0"
  "org.seedstack.addons.redis.version" = "2.0.0"
  "org.seedstack.addons.scheduling.version" = "3.2.0"
  "org.seedstack.addons.shell.version" = "1.0.1"
  "org.seedstack.addons.solr.version" = "2.0.0"
  "org.seedstack.addons.spring.version" = "3.1.1"
  "org.seedstack.addons.swagger.version" = "2.1.2"
  "org.seedstack.addons.w20.version" = "3.2.7"
  "org.seedstack.addons.web.version" = "1.0.3"
  "org.seedstack.addons.ws.version" = "3.0.3"

  "numRelatedPosts" = 2


[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    angledQuotes = true
    plainIdAnchors = true

[taxonomies]
  tag = "tags"
  technology = "technologies"

#####################################
#### Menu                        ####
#####################################

[[menu.learn-tutorial]]
    name = "Getting started"
    identifier = "getting-started"
    weight = -100

[[menu.learn-tutorial]]
    name = "Basics"
    identifier = "basics"
    weight = -90

[[menu.learn-tutorial]]
    name = "REST APIs"
    identifier = "rest"
    weight = -80

[[menu.learn-tutorial]]
    name = "Business & DDD"
    identifier = "business"
    weight = -70

[[menu.learn-samples]]
    name = "Categories"
    identifier = "categories"
    weight = -90

[[menu.learn-samples]]
    name = "Overview"
    identifier = "overview"
    weight = -100

[[menu.learn-guides]]
    name = "Contents"
    identifier = "contents"
    weight = -100

[[menu.project]]
    name = "Project info"
    identifier = "project"
    weight = -100
    url = "/project/"

[[menu.docs-core]]
    name = "Basics"
    identifier = "basics"
    weight = -90
    url = "/docs/core/basics/"

[[menu.docs-core]]
    name = "Command-line"
    identifier = "cli"
    weight = -85
    url = "/docs/core/cli/"

[[menu.docs-core]]
    name = "Web"
    identifier = "web"
    weight = -80
    url = "/docs/core/web/"

[[menu.docs-core]]
    name = "Advanced"
    identifier = "advanced"
    weight = -70
    url = "/docs/core/advanced/"

[[menu.docs-maven]]
    name = "Basics"
    identifier = "basics"
    weight = -30
    url = "/docs/maven/"

[[menu.docs-maven]]
    name = "Development goals"
    identifier = "development"
    weight = -20
    url = "/docs/maven/"

[[menu.docs-maven]]
    name = "Tool goals"
    identifier = "tools"
    weight = -10
    url = "/docs/maven/"

[[menu.docs-business]]
    name = "Basics"
    identifier = "basics"
    weight = -100
    url = "/docs/business/"

[[menu.docs-business]]
    name = "Tutorial"
    identifier = "tutorial"
    weight = -90
    url = "/docs/business/tutorial"

[[menu.docs-business]]
    name = "Modeling"
    identifier = "model"
    weight = -80
    url = "/docs/business/"

[[menu.docs-business]]
    name = "Behavior"
    identifier = "behavior"
    weight = -60
    url = "/docs/business/"

[[menu.docs-business]]
    name = "Interfaces"
    identifier = "interfaces"
    weight = -40
    url = "/docs/business/"

[[menu.addons]]
    name = "Contents"
    identifier = "contents"
    weight = -100
    url = "/addons/"



#####################################
#### Sections                    ####
#####################################

[params.sections.Learn]
  path = "learn"
  label = "Learn"
  logo = "getting-started-logo.svg"

[params.sections.Docs]
  path = "glossary"
  label = "Glossary"
  logo = "glossary-logo.svg"

[params.sections.Addons]
  path = "addons"
  label = "Add-ons"
  logo = "addons-logo.svg"

[params.sections.Support]
  path = "project"
  label = "Project"
  logo = "project-logo.svg"

[params.sections.Posts]
  path = "posts"
  label = "Posts"
  logo = "news-logo.svg"

[params.sections.Search]
  path = "search"
  label = "Search"
  logo = "search-logo.svg"

